services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: ducklake-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ducklake
      POSTGRES_PASSWORD: ducklake
      POSTGRES_DB: ducklake_catalog
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ducklake"]
      interval: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: ducklake-minio
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 5s
      retries: 5

  ducklake-init:
    build: ./ducklake-init
    container_name: ducklake-init
    environment:
      # Postgres catalog
      POSTGRES_USER: ducklake
      POSTGRES_PASSWORD: ducklake
      POSTGRES_DB: ducklake_catalog
      # S3 (MinIO) creds
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      BUCKET: ducklake
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ducklake-data:/data

volumes:
  pgdata:
  miniodata:
  ducklake-data: