name: Docker Compose CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run demo and verify data
        run: |
          # Run the demo which builds, starts services, and loads sample data
          make demo
          
          # Verify that data was actually loaded by checking row count
          echo "Verifying demo data was loaded..."
          row_count=$(docker compose exec -T ducklake-init duckdb -c "SELECT COUNT(*) FROM the_ducklake.gene;" | tail -n 1 | tr -d ' ')
          echo "Found $row_count rows in gene table"
          
          # Ensure we have a reasonable number of rows (gene data should have thousands)
          if [ "$row_count" -gt 1000 ]; then
            echo "✅ Demo successful: $row_count rows loaded"
          else
            echo "❌ Demo failed: only $row_count rows found (expected > 1000)"
            exit 1
          fi

      - name: Test basic DuckLake functionality
        run: |
          # Test connection and basic queries
          make test-connection
          
          # Run additional smoke tests
          echo "Running additional smoke tests..."
          docker compose exec -T ducklake-init duckdb -c "
            -- Test table exists and has data
            SELECT 'gene table exists' as test, COUNT(*) > 0 as result FROM the_ducklake.gene;
            
            -- Test we can query specific columns
            SELECT 'column access test' as test, COUNT(DISTINCT symbol) > 100 as result 
            FROM the_ducklake.gene 
            WHERE symbol IS NOT NULL;
            
            -- Test basic aggregation works
            SELECT 'aggregation test' as test, COUNT(*) as total_rows, COUNT(DISTINCT symbol) as unique_symbols
            FROM the_ducklake.gene;
          "

      - name: Clean up
        if: always()
        run: make down